--- 
abstract: Catalyst based application
author: root
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: hapConfig
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7010
  YAML: 0
version: 0.90
